
name: Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm ci
      working-directory: frontend
    - name: react-scripts test
      run: npm test
      working-directory: frontend